-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj1\hdlsrc\gaussianFilter\gaussianF_ip_dut.vhd
-- Created: 2024-06-04 15:10:22
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gaussianF_ip_dut
-- Source Path: gaussianF_ip/gaussianF_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY gaussianF_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        imageIn                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        imageIn_valid                     :   IN    std_logic;  -- ufix1
        imageOut_ready                    :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        imageOut                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        imageOut_valid                    :   OUT   std_logic;  -- ufix1
        imageIn_ready                     :   OUT   std_logic  -- ufix1
        );
END gaussianF_ip_dut;


ARCHITECTURE rtl OF gaussianF_ip_dut IS

  -- Component Declarations
  COMPONENT gaussianF_ip_src_gaussianFilter
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          imageIn                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          imageIn_valid                   :   IN    std_logic;  -- ufix1
          imageOut_ready                  :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          imageOut                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          imageOut_valid                  :   OUT   std_logic;  -- ufix1
          imageIn_ready                   :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : gaussianF_ip_src_gaussianFilter
    USE ENTITY work.gaussianF_ip_src_gaussianFilter(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL imageOut_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL imageOut_valid_sig               : std_logic;  -- ufix1
  SIGNAL imageIn_ready_sig                : std_logic;  -- ufix1

BEGIN
  u_gaussianF_ip_src_gaussianFilter : gaussianF_ip_src_gaussianFilter
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              imageIn => imageIn,  -- ufix32
              imageIn_valid => imageIn_valid,  -- ufix1
              imageOut_ready => imageOut_ready,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              imageOut => imageOut_sig,  -- ufix32
              imageOut_valid => imageOut_valid_sig,  -- ufix1
              imageIn_ready => imageIn_ready_sig  -- ufix1
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  imageOut_valid <= imageOut_valid_sig;

  imageIn_ready <= imageIn_ready_sig;

  imageOut <= imageOut_sig;

END rtl;

