%% Main entry point for Simulink model end results analysis.
function detections = SoftwarePipeline(gray, raw_segments)
    % Step 7b
    correctedSegments = SegmentCorrection(...
        raw_segments(1), raw_segments(2),...
        raw_segments(3), raw_segments(4),...
        raw_segments(5),...
        Pt2PtDist(...
            raw_segments(1), raw_segments(2),...
            raw_segments(3), raw_segments(4))...
        );
    % Step 8
    connectedSegments = SegmentConnection(correctedSegments);
    % Step 9
    quads = CreateQuads(connectedSegments, correctedSegments);
    % Step 10
    detections = DecodeQuads(quads, single(gray));
    % Step 11
    detections = DuplicationRemoval(detections);
    % Step 12
    % PoseEstimation is already done...
end