-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj3\hdlsrc\gaussianFilter\gaussianF_ip_src_Output_FIFOs.vhd
-- Created: 2024-06-04 12:27:51
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gaussianF_ip_src_Output_FIFOs
-- Source Path: gaussianFilter/gaussianFilter/Output_FIFOs
-- Hierarchy Level: 1
-- Model version: 8.37
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY gaussianF_ip_src_Output_FIFOs IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enable_in                         :   IN    std_logic;
        y_in                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        y_valid_in                        :   IN    std_logic;
        y_ready                           :   IN    std_logic;
        enable_out                        :   OUT   std_logic;
        y_out                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        y_valid                           :   OUT   std_logic
        );
END gaussianF_ip_src_Output_FIFOs;


ARCHITECTURE rtl OF gaussianF_ip_src_Output_FIFOs IS

  -- Component Declarations
  COMPONENT gaussianF_ip_src_y_FIFO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          y_in                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          valid_in                        :   IN    std_logic;
          enable                          :   IN    std_logic;
          ready_in                        :   IN    std_logic;
          y_out                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          y_valid                         :   OUT   std_logic;
          y_has_space                     :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : gaussianF_ip_src_y_FIFO
    USE ENTITY work.gaussianF_ip_src_y_FIFO(rtl);

  -- Signals
  SIGNAL y_out_tmp                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL y_has_space                      : std_logic;

BEGIN
  u_y_FIFO : gaussianF_ip_src_y_FIFO
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              y_in => y_in,  -- uint32
              valid_in => y_valid_in,
              enable => enable_in,
              ready_in => y_ready,
              y_out => y_out_tmp,  -- uint32
              y_valid => y_valid,
              y_has_space => y_has_space
              );

  enable_out <= y_has_space;

  y_out <= y_out_tmp;

END rtl;

