-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj3\hdlsrc\gaussianFilter\gaussianF_ip_src_nfp_recip_single.vhd
-- Created: 2024-06-04 12:27:50
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gaussianF_ip_src_nfp_recip_single
-- Source Path: gaussianFilter/gaussianFilter/singleToUint32/nfp_recip_single
-- Hierarchy Level: 2
-- Model version: 8.37
-- 
-- {Latency Strategy = "Min", Denormal Handling = "off"}
-- {Radix = "2"}
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.gaussianF_ip_src_gaussianFilter_pkg.ALL;

ENTITY gaussianF_ip_src_nfp_recip_single IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        nfp_in                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        nfp_out                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END gaussianF_ip_src_nfp_recip_single;


ARCHITECTURE rtl OF gaussianF_ip_src_nfp_recip_single IS

  -- Signals
  SIGNAL Constant8_out1                   : std_logic;  -- ufix1
  SIGNAL Constant7_out1                   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Relational_Operator_out1         : std_logic;  -- ufix1
  SIGNAL Delay4_out1                      : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1            : std_logic;  -- ufix1
  SIGNAL Add_out1                         : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Delay3_out1                      : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Add_add_cast                     : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Delay1_out1                      : std_logic;  -- ufix1
  SIGNAL nfp_in_unsigned                  : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL aSign                            : std_logic;  -- ufix1
  SIGNAL aExponent                        : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL aMantissa                        : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Delay_P1_out1                    : std_logic;  -- ufix1
  SIGNAL Delay19_P5_28_reg                : std_logic_vector(13 DOWNTO 0);  -- ufix1 [14]
  SIGNAL Delay19_P5_28_out1               : std_logic;  -- ufix1
  SIGNAL Constant1_out1                   : std_logic;  -- ufix1
  SIGNAL Switch1_out1                     : std_logic;  -- ufix1
  SIGNAL Delay3_out1_1                    : std_logic;  -- ufix1
  SIGNAL Delay1_P1_out1                   : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL aExponent_cfType_Exponent_I_out1 : std_logic;  -- ufix1
  SIGNAL aExponent_0_out1                 : std_logic;  -- ufix1
  SIGNAL Delay2_P1_out1                   : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Constant_out1                    : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Switch_out1                      : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL aMantissa_0_out1                 : std_logic;  -- ufix1
  SIGNAL alphaaExponent_0_aMantissa_out1  : std_logic;  -- ufix1
  SIGNAL alphaaExponent_cfType_Exponent_out1 : std_logic;  -- ufix1
  SIGNAL Delay12_P5_28_reg                : std_logic_vector(13 DOWNTO 0);  -- ufix1 [14]
  SIGNAL Delay12_P5_28_out1               : std_logic;  -- ufix1
  SIGNAL alpha0_out1                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL alphaExponent_0_cfType_Exp_out1  : std_logic;
  SIGNAL alpha1_out1                      : std_logic;  -- ufix1
  SIGNAL alpha0_out1_1                    : std_logic;  -- ufix1
  SIGNAL if_Exponent_0_cfType_Exp_out1    : std_logic;  -- ufix1
  SIGNAL Bit_Concat1_out1                 : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Bit_Concat_out1                  : unsigned(25 DOWNTO 0);  -- ufix26
  SIGNAL reinterpretcast_bitconcat_fi_0_out1 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay4_P3_out1                   : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL BitSlice_out1                    : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL bitsliceget_mant_a_cfType_Man_out1 : std_logic;
  SIGNAL Delay2_P4_out1                   : std_logic;
  SIGNAL c2_out1                          : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Delay1_P1_out1_dtc               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL C_out1                           : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL if_Exponent_0_out1               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL DTC_out1                         : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Delay3_P3_out1                   : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Delay3_P4_out1                   : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL sub1_out1                        : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL c1_out1                          : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL sub2_out1                        : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL s0_out1                          : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL relop2_out1                      : std_logic;
  SIGNAL relop3_out1                      : std_logic;
  SIGNAL C3_out1                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relop1_out1                      : std_logic;
  SIGNAL C1_out1_1                        : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL C_out1_1                         : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s1_out1                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s3_out1                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL C5_out1                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s4_out1                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Delay11_P5_28_reg                : vector_of_unsigned5(0 TO 11);  -- ufix5 [12]
  SIGNAL Delay11_P5_28_out1               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL shift_length_1_out1              : std_logic;
  SIGNAL shift_length_1_out1_1            : std_logic;
  SIGNAL C_out1_2                         : std_logic;  -- ufix1
  SIGNAL C1_out1_2                        : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL C_out1_3                         : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL if_bitsliceget_mant_a_cfType_Ma_out1 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay1_P4_out1                   : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Unary_Minus_in0                  : signed(26 DOWNTO 0);  -- sfix27
  SIGNAL Unary_Minus_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay_P4_out1                    : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_1             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1                   : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_1          : std_logic;
  SIGNAL Bit_Concat_out1_1                : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Delay3_P6_out1                   : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL if_tmp_0_1_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_1                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay4_P6_out1                   : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay5_P6_out1                   : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_2             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_1                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_2          : std_logic;
  SIGNAL Bit_Concat_out1_2                : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL if_tmp_0_1_out1_1                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_2                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_3             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_2                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_3          : std_logic;
  SIGNAL Bit_Concat_out1_3                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Delay9_P8_out1                   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL if_tmp_0_1_out1_2                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_3                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay10_P8_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay11_P8_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_4             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_3                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_4          : std_logic;
  SIGNAL Bit_Concat_out1_4                : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL if_tmp_0_1_out1_3                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_4                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_5             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_4                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_5          : std_logic;
  SIGNAL Bit_Concat_out1_5                : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Delay_P10_out1                   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL if_tmp_0_1_out1_4                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_5                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay1_P10_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay2_P10_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_6             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_5                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_6          : std_logic;
  SIGNAL Bit_Concat_out1_6                : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL if_tmp_0_1_out1_5                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_6                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_7             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_6                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_7          : std_logic;
  SIGNAL Bit_Concat_out1_7                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay6_P12_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL if_tmp_0_1_out1_6                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_7                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay7_P12_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay8_P12_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_8             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_7                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_8          : std_logic;
  SIGNAL Bit_Concat_out1_8                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL if_tmp_0_1_out1_7                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_8                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_9             : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_8                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_9          : std_logic;
  SIGNAL Bit_Concat_out1_9                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Delay3_P14_out1                  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL if_tmp_0_1_out1_8                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_9                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay4_P14_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay5_P14_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_10            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_9                 : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_10         : std_logic;
  SIGNAL Bit_Concat_out1_10               : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL if_tmp_0_1_out1_9                : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_10               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_11            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_10                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_11         : std_logic;
  SIGNAL Bit_Concat_out1_11               : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Delay3_P16_out1                  : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL if_tmp_0_1_out1_10               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_11               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay4_P16_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay5_P16_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_12            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_11                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_12         : std_logic;
  SIGNAL Bit_Concat_out1_12               : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL if_tmp_0_1_out1_11               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_12               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_13            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_12                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_13         : std_logic;
  SIGNAL Bit_Concat_out1_13               : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL Delay9_P18_out1                  : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL if_tmp_0_1_out1_12               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_13               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay10_P18_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay11_P18_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_14            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_13                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_14         : std_logic;
  SIGNAL Bit_Concat_out1_14               : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL if_tmp_0_1_out1_13               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_14               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_15            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_14                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_15         : std_logic;
  SIGNAL Bit_Concat_out1_15               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_P20_out1                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL if_tmp_0_1_out1_14               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_15               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay1_P20_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay2_P20_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_16            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_15                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_16         : std_logic;
  SIGNAL Bit_Concat_out1_16               : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL if_tmp_0_1_out1_15               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_16               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_17            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_16                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_17         : std_logic;
  SIGNAL Bit_Concat_out1_17               : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Delay6_P22_out1                  : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL if_tmp_0_1_out1_16               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_17               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay7_P22_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay8_P22_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_18            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_17                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_18         : std_logic;
  SIGNAL Bit_Concat_out1_18               : unsigned(18 DOWNTO 0);  -- ufix19
  SIGNAL if_tmp_0_1_out1_17               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_18               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_19            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_18                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_19         : std_logic;
  SIGNAL Bit_Concat_out1_19               : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL Delay9_P24_out1                  : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL if_tmp_0_1_out1_18               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_19               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay10_P24_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay11_P24_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_20            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_19                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_20         : std_logic;
  SIGNAL Bit_Concat_out1_20               : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL if_tmp_0_1_out1_19               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_20               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_21            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_20                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_21         : std_logic;
  SIGNAL Bit_Concat_out1_21               : unsigned(21 DOWNTO 0);  -- ufix22
  SIGNAL Delay3_P26_out1                  : unsigned(21 DOWNTO 0);  -- ufix22
  SIGNAL if_tmp_0_1_out1_20               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_21               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay4_P26_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay5_P26_out1                  : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_22            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_21                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_22         : std_logic;
  SIGNAL Bit_Concat_out1_22               : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL if_tmp_0_1_out1_21               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_22               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_23            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_22                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_23         : std_logic;
  SIGNAL Bit_Concat_out1_23               : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Delay9_P28_out1                  : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL if_tmp_0_1_out1_22               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL bitsll_R_1_out1_23               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay10_P28_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay11_P28_out1                 : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_mant_b_norm_out1_24            : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Bit_Slice_out1_23                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_24         : std_logic;
  SIGNAL Bit_Concat_out1_24               : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL C_out1_4                         : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL if_shift_length_1_out1           : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL bitsrl_Q_1_out1                  : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL if_shift_length_1_out1_1         : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL BitSlice_out1_1                  : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Bit_Slice10_out1                 : std_logic;  -- ufix1
  SIGNAL Bit_Slice9_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice7_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice8_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice11_out1                 : std_logic;  -- ufix1
  SIGNAL Bit_Slice_out1_24                : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Constant_out1_1                  : std_logic;  -- ufix1
  SIGNAL Bit_Concat_out1_25               : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Slice_out1_25                : std_logic;  -- ufix1
  SIGNAL Bit_Slice1_out1                  : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_25         : std_logic;
  SIGNAL Switch6_out1                     : std_logic;
  SIGNAL Bit_Slice2_out1                  : std_logic;  -- ufix1
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Bit_Slice3_out1                  : std_logic;  -- ufix1
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Switch7_out1                     : std_logic;
  SIGNAL Switch3_out1                     : std_logic;
  SIGNAL Bit_Slice1_out1_1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Slice_out1_26                : std_logic;  -- ufix1
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL Bit_Slice1_out1_2                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_26         : std_logic;
  SIGNAL Switch6_out1_1                   : std_logic;
  SIGNAL Bit_Slice2_out1_1                : std_logic;  -- ufix1
  SIGNAL Logical_Operator1_out1_1         : std_logic;
  SIGNAL Bit_Slice3_out1_1                : std_logic;  -- ufix1
  SIGNAL Logical_Operator2_out1_1         : std_logic;
  SIGNAL Switch7_out1_1                   : std_logic;
  SIGNAL Switch3_out1_1                   : std_logic;
  SIGNAL Switch6_out1_2                   : std_logic;
  SIGNAL Bit_Slice2_out1_2                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Slice_out1_27                : std_logic;  -- ufix1
  SIGNAL Logical_Operator3_out1_1         : std_logic;
  SIGNAL Bit_Slice1_out1_3                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_27         : std_logic;
  SIGNAL Switch6_out1_3                   : std_logic;
  SIGNAL Bit_Slice2_out1_3                : std_logic;  -- ufix1
  SIGNAL Logical_Operator1_out1_2         : std_logic;
  SIGNAL Bit_Slice3_out1_2                : std_logic;  -- ufix1
  SIGNAL Logical_Operator2_out1_2         : std_logic;
  SIGNAL Switch7_out1_2                   : std_logic;
  SIGNAL Switch3_out1_2                   : std_logic;
  SIGNAL Bit_Slice3_out1_3                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Slice_out1_28                : std_logic;  -- ufix1
  SIGNAL Logical_Operator3_out1_2         : std_logic;
  SIGNAL Bit_Slice1_out1_4                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_28         : std_logic;
  SIGNAL Switch6_out1_4                   : std_logic;
  SIGNAL Bit_Slice2_out1_4                : std_logic;  -- ufix1
  SIGNAL Logical_Operator1_out1_3         : std_logic;
  SIGNAL Bit_Slice3_out1_4                : std_logic;  -- ufix1
  SIGNAL Logical_Operator2_out1_3         : std_logic;
  SIGNAL Switch7_out1_3                   : std_logic;
  SIGNAL Switch3_out1_3                   : std_logic;
  SIGNAL Switch7_out1_4                   : std_logic;
  SIGNAL Switch3_out1_4                   : std_logic;
  SIGNAL Bit_Slice4_out1                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Slice_out1_29                : std_logic;  -- ufix1
  SIGNAL Logical_Operator3_out1_3         : std_logic;
  SIGNAL Bit_Slice1_out1_5                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_29         : std_logic;
  SIGNAL Switch6_out1_5                   : std_logic;
  SIGNAL Bit_Slice2_out1_5                : std_logic;  -- ufix1
  SIGNAL Logical_Operator1_out1_4         : std_logic;
  SIGNAL Bit_Slice3_out1_5                : std_logic;  -- ufix1
  SIGNAL Logical_Operator2_out1_4         : std_logic;
  SIGNAL Switch7_out1_5                   : std_logic;
  SIGNAL Switch3_out1_5                   : std_logic;
  SIGNAL Bit_Slice5_out1                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Slice_out1_30                : std_logic;  -- ufix1
  SIGNAL Logical_Operator3_out1_4         : std_logic;
  SIGNAL Bit_Slice1_out1_6                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_30         : std_logic;
  SIGNAL Switch6_out1_6                   : std_logic;
  SIGNAL Bit_Slice2_out1_6                : std_logic;  -- ufix1
  SIGNAL Logical_Operator1_out1_5         : std_logic;
  SIGNAL Bit_Slice3_out1_6                : std_logic;  -- ufix1
  SIGNAL Logical_Operator2_out1_5         : std_logic;
  SIGNAL Switch7_out1_6                   : std_logic;
  SIGNAL Switch3_out1_6                   : std_logic;
  SIGNAL Switch4_out1                     : std_logic;
  SIGNAL Logical_Operator_out1_31         : std_logic;
  SIGNAL Bit_Slice6_out1                  : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Bit_Slice_out1_31                : std_logic;  -- ufix1
  SIGNAL Logical_Operator3_out1_5         : std_logic;
  SIGNAL Bit_Slice1_out1_7                : std_logic;  -- ufix1
  SIGNAL Logical_Operator_out1_32         : std_logic;
  SIGNAL Switch7_out1_7                   : std_logic;
  SIGNAL BitSlice_out1_2                  : std_logic;  -- ufix1
  SIGNAL BitSlice1_out1                   : std_logic;  -- ufix1
  SIGNAL if_tmp_0_1_out1_23               : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL R_0_out1                         : std_logic;
  SIGNAL Switch1_out1_1                   : std_logic;
  SIGNAL Switch2_out1                     : std_logic;
  SIGNAL sticky_bitsll_Q_Q_WordLen_out1   : std_logic;
  SIGNAL alphabitget_Mant_tmp_2_0_out1    : std_logic;
  SIGNAL alphabitget_Mant_tmp_1_0_out1    : std_logic;
  SIGNAL alpha0_out1_2                    : std_logic;  -- ufix1
  SIGNAL Bit_Concat_out1_26               : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL alpha2_out1                      : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL Mant_tmp_2_out1                  : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL if_bitget_Mant_tmp_1_0_out1      : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL BitSlice2_out1                   : std_logic;  -- ufix1
  SIGNAL DTC2_out1                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL C2_out1_1                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL s2_out1                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL C4_out1                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL s5_out1                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay12_P5_28_reg_1              : vector_of_unsigned8(0 TO 11);  -- ufix8 [12]
  SIGNAL Delay12_P5_28_out1_1             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL alpha1_out1_1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Exp_1_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL if_bitget_Mant_tmp_Mant_tmp_Wor_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL C2_out1_2                        : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL C_out1_5                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL if_mant_a_0_out1                 : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL if_exp_a_cfType_Exponent_Inf_out1 : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Delay16_P5_28_reg                : vector_of_unsigned8(0 TO 13);  -- ufix8 [14]
  SIGNAL Delay16_P5_28_out1               : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL if_aExponent_cfType_Exponent_out1 : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Constant3_out1                   : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Switch6_out1_7                   : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Delay4_out1_1                    : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL Logical_Operator_out1_33         : std_logic;
  SIGNAL BitSlice3_out1                   : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL C_out1_6                         : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL if_bitget_Mant_tmp_Mant_tmp_Wor_1_out1 : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL C3_out1_1                        : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL if_exp_a_cfType_Exponent_Inf_1_out1 : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Delay13_P5_28_reg                : vector_of_unsigned23(0 TO 13);  -- ufix23 [14]
  SIGNAL Delay13_P5_28_out1               : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL if_aExponent_cfType_Exponent_1_out1 : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Constant2_out1                   : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Switch5_out1                     : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL Delay5_out1                      : unsigned(22 DOWNTO 0);  -- ufix23
  SIGNAL nfp_out_pack                     : unsigned(31 DOWNTO 0);  -- ufix32

BEGIN
  Constant8_out1 <= '1';

  Constant7_out1 <= to_unsigned(16#0E#, 6);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= '1';
      ELSIF enb = '1' THEN
        Delay4_out1 <= Relational_Operator_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Logical_Operator_out1 <= Constant8_out1 AND Delay4_out1;

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= to_unsigned(16#00#, 6);
      ELSIF enb = '1' THEN
        Delay3_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Add_add_cast <= '0' & '0' & '0' & '0' & '0' & Logical_Operator_out1;
  Add_out1 <= Delay3_out1 + Add_add_cast;

  
  Relational_Operator_out1 <= '1' WHEN Add_out1 <= Constant7_out1 ELSE
      '0';

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= '1';
      ELSIF enb = '1' THEN
        Delay1_out1 <= Relational_Operator_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  nfp_in_unsigned <= unsigned(nfp_in);

  -- Split 32 bit word into FP sign, exponent, mantissa
  aSign <= nfp_in_unsigned(31);
  aExponent <= nfp_in_unsigned(30 DOWNTO 23);
  aMantissa <= nfp_in_unsigned(22 DOWNTO 0);

  Delay_P1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_P1_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay_P1_out1 <= aSign;
      END IF;
    END IF;
  END PROCESS Delay_P1_process;


  Delay19_P5_28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay19_P5_28_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay19_P5_28_reg(0) <= Delay_P1_out1;
        Delay19_P5_28_reg(13 DOWNTO 1) <= Delay19_P5_28_reg(12 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay19_P5_28_process;

  Delay19_P5_28_out1 <= Delay19_P5_28_reg(13);

  Constant1_out1 <= '0';

  
  Switch1_out1 <= Delay19_P5_28_out1 WHEN Delay1_out1 = '0' ELSE
      Constant1_out1;

  Delay3_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1_1 <= '0';
      ELSIF enb = '1' THEN
        Delay3_out1_1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Delay3_1_process;


  Delay1_P1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_P1_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay1_P1_out1 <= aExponent;
      END IF;
    END IF;
  END PROCESS Delay1_P1_process;


  
  aExponent_cfType_Exponent_I_out1 <= '1' WHEN Delay1_P1_out1 = to_unsigned(16#FF#, 8) ELSE
      '0';

  
  aExponent_0_out1 <= '1' WHEN Delay1_P1_out1 = to_unsigned(16#00#, 8) ELSE
      '0';

  Delay2_P1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_P1_out1 <= to_unsigned(16#000000#, 23);
      ELSIF enb = '1' THEN
        Delay2_P1_out1 <= aMantissa;
      END IF;
    END IF;
  END PROCESS Delay2_P1_process;


  Constant_out1 <= to_unsigned(16#000000#, 23);

  
  Switch_out1 <= Delay2_P1_out1 WHEN aExponent_0_out1 = '0' ELSE
      Constant_out1;

  
  aMantissa_0_out1 <= '1' WHEN Switch_out1 = to_unsigned(16#000000#, 23) ELSE
      '0';

  alphaaExponent_0_aMantissa_out1 <= aExponent_0_out1 AND aMantissa_0_out1;

  alphaaExponent_cfType_Exponent_out1 <= aExponent_cfType_Exponent_I_out1 OR alphaaExponent_0_aMantissa_out1;

  Delay12_P5_28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay12_P5_28_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay12_P5_28_reg(0) <= alphaaExponent_cfType_Exponent_out1;
        Delay12_P5_28_reg(13 DOWNTO 1) <= Delay12_P5_28_reg(12 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay12_P5_28_process;

  Delay12_P5_28_out1 <= Delay12_P5_28_reg(13);

  alpha0_out1 <= to_unsigned(16#0#, 2);

  alphaExponent_0_cfType_Exp_out1 <= aExponent_0_out1 OR aExponent_cfType_Exponent_I_out1;

  alpha1_out1 <= '1';

  alpha0_out1_1 <= '0';

  
  if_Exponent_0_cfType_Exp_out1 <= alpha1_out1 WHEN alphaExponent_0_cfType_Exp_out1 = '0' ELSE
      alpha0_out1_1;

  Bit_Concat1_out1 <= if_Exponent_0_cfType_Exp_out1 & Switch_out1;

  Bit_Concat_out1 <= alpha0_out1 & Bit_Concat1_out1;

  reinterpretcast_bitconcat_fi_0_out1 <= signed(Bit_Concat_out1);

  Delay4_P3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_P3_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay4_P3_out1 <= reinterpretcast_bitconcat_fi_0_out1;
      END IF;
    END IF;
  END PROCESS Delay4_P3_process;


  BitSlice_out1 <= unsigned(Delay4_P3_out1(22 DOWNTO 0));

  
  bitsliceget_mant_a_cfType_Man_out1 <= '1' WHEN BitSlice_out1 /= to_unsigned(16#000000#, 23) ELSE
      '0';

  Delay2_P4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_P4_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay2_P4_out1 <= bitsliceget_mant_a_cfType_Man_out1;
      END IF;
    END IF;
  END PROCESS Delay2_P4_process;


  c2_out1 <= to_signed(16#0FE#, 10);

  Delay1_P1_out1_dtc <= Delay1_P1_out1;

  C_out1 <= to_unsigned(16#01#, 8);

  
  if_Exponent_0_out1 <= Delay1_P1_out1_dtc WHEN aExponent_0_out1 = '0' ELSE
      C_out1;

  DTC_out1 <= signed(resize(if_Exponent_0_out1, 10));

  Delay3_P3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_P3_out1 <= to_signed(16#000#, 10);
      ELSIF enb = '1' THEN
        Delay3_P3_out1 <= DTC_out1;
      END IF;
    END IF;
  END PROCESS Delay3_P3_process;


  Delay3_P4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_P4_out1 <= to_signed(16#000#, 10);
      ELSIF enb = '1' THEN
        Delay3_P4_out1 <= Delay3_P3_out1;
      END IF;
    END IF;
  END PROCESS Delay3_P4_process;


  sub1_out1 <= c2_out1 - Delay3_P4_out1;

  c1_out1 <= to_signed(16#0FD#, 10);

  sub2_out1 <= c1_out1 - Delay3_P4_out1;

  
  s0_out1 <= sub1_out1 WHEN Delay2_P4_out1 = '0' ELSE
      sub2_out1;

  
  relop2_out1 <= '1' WHEN s0_out1 >= to_signed(16#0FF#, 10) ELSE
      '0';

  
  relop3_out1 <= '1' WHEN s0_out1 < to_signed(16#001#, 10) ELSE
      '0';

  C3_out1 <= to_unsigned(16#00#, 5);

  
  relop1_out1 <= '1' WHEN s0_out1 = to_signed(16#000#, 10) ELSE
      '0';

  C1_out1_1 <= to_unsigned(16#19#, 5);

  C_out1_1 <= to_unsigned(16#01#, 5);

  
  s1_out1 <= C1_out1_1 WHEN relop1_out1 = '0' ELSE
      C_out1_1;

  
  s3_out1 <= C3_out1 WHEN relop3_out1 = '0' ELSE
      s1_out1;

  C5_out1 <= to_unsigned(16#19#, 5);

  
  s4_out1 <= s3_out1 WHEN relop2_out1 = '0' ELSE
      C5_out1;

  Delay11_P5_28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_P5_28_reg <= (OTHERS => to_unsigned(16#00#, 5));
      ELSIF enb = '1' THEN
        Delay11_P5_28_reg(0) <= s4_out1;
        Delay11_P5_28_reg(1 TO 11) <= Delay11_P5_28_reg(0 TO 10);
      END IF;
    END IF;
  END PROCESS Delay11_P5_28_process;

  Delay11_P5_28_out1 <= Delay11_P5_28_reg(11);

  
  shift_length_1_out1 <= '1' WHEN Delay11_P5_28_out1 = to_unsigned(16#01#, 5) ELSE
      '0';

  
  shift_length_1_out1_1 <= '1' WHEN Delay11_P5_28_out1 > to_unsigned(16#01#, 5) ELSE
      '0';

  C_out1_2 <= '1';

  C1_out1_2 <= to_signed(16#0800000#, 26);

  C_out1_3 <= to_signed(16#1000000#, 26);

  
  if_bitsliceget_mant_a_cfType_Ma_out1 <= C1_out1_2 WHEN bitsliceget_mant_a_cfType_Man_out1 = '0' ELSE
      C_out1_3;

  Delay1_P4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_P4_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay1_P4_out1 <= if_bitsliceget_mant_a_cfType_Ma_out1;
      END IF;
    END IF;
  END PROCESS Delay1_P4_process;


  Unary_Minus_in0 <=  - (resize(Delay4_P3_out1, 27));
  Unary_Minus_out1 <= Unary_Minus_in0(25 DOWNTO 0);

  Delay_P4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_P4_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay_P4_out1 <= Unary_Minus_out1;
      END IF;
    END IF;
  END PROCESS Delay_P4_process;


  R_mant_b_norm_out1 <= Delay1_P4_out1 + Delay_P4_out1;

  bitsll_R_1_out1 <= R_mant_b_norm_out1 sll 1;

  R_mant_b_norm_out1_1 <= bitsll_R_1_out1 + Delay_P4_out1;

  Bit_Slice_out1 <= R_mant_b_norm_out1_1(25);

  Logical_Operator_out1_1 <=  NOT Bit_Slice_out1;

  Bit_Concat_out1_1 <= unsigned'(C_out1_2 & Logical_Operator_out1_1);

  Delay3_P6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_P6_out1 <= to_unsigned(16#0#, 2);
      ELSIF enb = '1' THEN
        Delay3_P6_out1 <= Bit_Concat_out1_1;
      END IF;
    END IF;
  END PROCESS Delay3_P6_process;


  
  if_tmp_0_1_out1 <= R_mant_b_norm_out1_1 WHEN Bit_Slice_out1 = '0' ELSE
      bitsll_R_1_out1;

  bitsll_R_1_out1_1 <= if_tmp_0_1_out1 sll 1;

  Delay4_P6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_P6_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay4_P6_out1 <= bitsll_R_1_out1_1;
      END IF;
    END IF;
  END PROCESS Delay4_P6_process;


  Delay5_P6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_P6_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay5_P6_out1 <= Delay_P4_out1;
      END IF;
    END IF;
  END PROCESS Delay5_P6_process;


  R_mant_b_norm_out1_2 <= Delay4_P6_out1 + Delay5_P6_out1;

  Bit_Slice_out1_1 <= R_mant_b_norm_out1_2(25);

  Logical_Operator_out1_2 <=  NOT Bit_Slice_out1_1;

  Bit_Concat_out1_2 <= Delay3_P6_out1 & Logical_Operator_out1_2;

  
  if_tmp_0_1_out1_1 <= R_mant_b_norm_out1_2 WHEN Bit_Slice_out1_1 = '0' ELSE
      Delay4_P6_out1;

  bitsll_R_1_out1_2 <= if_tmp_0_1_out1_1 sll 1;

  R_mant_b_norm_out1_3 <= bitsll_R_1_out1_2 + Delay5_P6_out1;

  Bit_Slice_out1_2 <= R_mant_b_norm_out1_3(25);

  Logical_Operator_out1_3 <=  NOT Bit_Slice_out1_2;

  Bit_Concat_out1_3 <= Bit_Concat_out1_2 & Logical_Operator_out1_3;

  Delay9_P8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_P8_out1 <= to_unsigned(16#0#, 4);
      ELSIF enb = '1' THEN
        Delay9_P8_out1 <= Bit_Concat_out1_3;
      END IF;
    END IF;
  END PROCESS Delay9_P8_process;


  
  if_tmp_0_1_out1_2 <= R_mant_b_norm_out1_3 WHEN Bit_Slice_out1_2 = '0' ELSE
      bitsll_R_1_out1_2;

  bitsll_R_1_out1_3 <= if_tmp_0_1_out1_2 sll 1;

  Delay10_P8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_P8_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay10_P8_out1 <= bitsll_R_1_out1_3;
      END IF;
    END IF;
  END PROCESS Delay10_P8_process;


  Delay11_P8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_P8_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay11_P8_out1 <= Delay5_P6_out1;
      END IF;
    END IF;
  END PROCESS Delay11_P8_process;


  R_mant_b_norm_out1_4 <= Delay10_P8_out1 + Delay11_P8_out1;

  Bit_Slice_out1_3 <= R_mant_b_norm_out1_4(25);

  Logical_Operator_out1_4 <=  NOT Bit_Slice_out1_3;

  Bit_Concat_out1_4 <= Delay9_P8_out1 & Logical_Operator_out1_4;

  
  if_tmp_0_1_out1_3 <= R_mant_b_norm_out1_4 WHEN Bit_Slice_out1_3 = '0' ELSE
      Delay10_P8_out1;

  bitsll_R_1_out1_4 <= if_tmp_0_1_out1_3 sll 1;

  R_mant_b_norm_out1_5 <= bitsll_R_1_out1_4 + Delay11_P8_out1;

  Bit_Slice_out1_4 <= R_mant_b_norm_out1_5(25);

  Logical_Operator_out1_5 <=  NOT Bit_Slice_out1_4;

  Bit_Concat_out1_5 <= Bit_Concat_out1_4 & Logical_Operator_out1_5;

  Delay_P10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_P10_out1 <= to_unsigned(16#00#, 6);
      ELSIF enb = '1' THEN
        Delay_P10_out1 <= Bit_Concat_out1_5;
      END IF;
    END IF;
  END PROCESS Delay_P10_process;


  
  if_tmp_0_1_out1_4 <= R_mant_b_norm_out1_5 WHEN Bit_Slice_out1_4 = '0' ELSE
      bitsll_R_1_out1_4;

  bitsll_R_1_out1_5 <= if_tmp_0_1_out1_4 sll 1;

  Delay1_P10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_P10_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay1_P10_out1 <= bitsll_R_1_out1_5;
      END IF;
    END IF;
  END PROCESS Delay1_P10_process;


  Delay2_P10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_P10_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay2_P10_out1 <= Delay11_P8_out1;
      END IF;
    END IF;
  END PROCESS Delay2_P10_process;


  R_mant_b_norm_out1_6 <= Delay1_P10_out1 + Delay2_P10_out1;

  Bit_Slice_out1_5 <= R_mant_b_norm_out1_6(25);

  Logical_Operator_out1_6 <=  NOT Bit_Slice_out1_5;

  Bit_Concat_out1_6 <= Delay_P10_out1 & Logical_Operator_out1_6;

  
  if_tmp_0_1_out1_5 <= R_mant_b_norm_out1_6 WHEN Bit_Slice_out1_5 = '0' ELSE
      Delay1_P10_out1;

  bitsll_R_1_out1_6 <= if_tmp_0_1_out1_5 sll 1;

  R_mant_b_norm_out1_7 <= bitsll_R_1_out1_6 + Delay2_P10_out1;

  Bit_Slice_out1_6 <= R_mant_b_norm_out1_7(25);

  Logical_Operator_out1_7 <=  NOT Bit_Slice_out1_6;

  Bit_Concat_out1_7 <= Bit_Concat_out1_6 & Logical_Operator_out1_7;

  Delay6_P12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_P12_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay6_P12_out1 <= Bit_Concat_out1_7;
      END IF;
    END IF;
  END PROCESS Delay6_P12_process;


  
  if_tmp_0_1_out1_6 <= R_mant_b_norm_out1_7 WHEN Bit_Slice_out1_6 = '0' ELSE
      bitsll_R_1_out1_6;

  bitsll_R_1_out1_7 <= if_tmp_0_1_out1_6 sll 1;

  Delay7_P12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_P12_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay7_P12_out1 <= bitsll_R_1_out1_7;
      END IF;
    END IF;
  END PROCESS Delay7_P12_process;


  Delay8_P12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_P12_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay8_P12_out1 <= Delay2_P10_out1;
      END IF;
    END IF;
  END PROCESS Delay8_P12_process;


  R_mant_b_norm_out1_8 <= Delay7_P12_out1 + Delay8_P12_out1;

  Bit_Slice_out1_7 <= R_mant_b_norm_out1_8(25);

  Logical_Operator_out1_8 <=  NOT Bit_Slice_out1_7;

  Bit_Concat_out1_8 <= Delay6_P12_out1 & Logical_Operator_out1_8;

  
  if_tmp_0_1_out1_7 <= R_mant_b_norm_out1_8 WHEN Bit_Slice_out1_7 = '0' ELSE
      Delay7_P12_out1;

  bitsll_R_1_out1_8 <= if_tmp_0_1_out1_7 sll 1;

  R_mant_b_norm_out1_9 <= bitsll_R_1_out1_8 + Delay8_P12_out1;

  Bit_Slice_out1_8 <= R_mant_b_norm_out1_9(25);

  Logical_Operator_out1_9 <=  NOT Bit_Slice_out1_8;

  Bit_Concat_out1_9 <= Bit_Concat_out1_8 & Logical_Operator_out1_9;

  Delay3_P14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_P14_out1 <= to_unsigned(16#000#, 10);
      ELSIF enb = '1' THEN
        Delay3_P14_out1 <= Bit_Concat_out1_9;
      END IF;
    END IF;
  END PROCESS Delay3_P14_process;


  
  if_tmp_0_1_out1_8 <= R_mant_b_norm_out1_9 WHEN Bit_Slice_out1_8 = '0' ELSE
      bitsll_R_1_out1_8;

  bitsll_R_1_out1_9 <= if_tmp_0_1_out1_8 sll 1;

  Delay4_P14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_P14_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay4_P14_out1 <= bitsll_R_1_out1_9;
      END IF;
    END IF;
  END PROCESS Delay4_P14_process;


  Delay5_P14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_P14_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay5_P14_out1 <= Delay8_P12_out1;
      END IF;
    END IF;
  END PROCESS Delay5_P14_process;


  R_mant_b_norm_out1_10 <= Delay4_P14_out1 + Delay5_P14_out1;

  Bit_Slice_out1_9 <= R_mant_b_norm_out1_10(25);

  Logical_Operator_out1_10 <=  NOT Bit_Slice_out1_9;

  Bit_Concat_out1_10 <= Delay3_P14_out1 & Logical_Operator_out1_10;

  
  if_tmp_0_1_out1_9 <= R_mant_b_norm_out1_10 WHEN Bit_Slice_out1_9 = '0' ELSE
      Delay4_P14_out1;

  bitsll_R_1_out1_10 <= if_tmp_0_1_out1_9 sll 1;

  R_mant_b_norm_out1_11 <= bitsll_R_1_out1_10 + Delay5_P14_out1;

  Bit_Slice_out1_10 <= R_mant_b_norm_out1_11(25);

  Logical_Operator_out1_11 <=  NOT Bit_Slice_out1_10;

  Bit_Concat_out1_11 <= Bit_Concat_out1_10 & Logical_Operator_out1_11;

  Delay3_P16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_P16_out1 <= to_unsigned(16#000#, 12);
      ELSIF enb = '1' THEN
        Delay3_P16_out1 <= Bit_Concat_out1_11;
      END IF;
    END IF;
  END PROCESS Delay3_P16_process;


  
  if_tmp_0_1_out1_10 <= R_mant_b_norm_out1_11 WHEN Bit_Slice_out1_10 = '0' ELSE
      bitsll_R_1_out1_10;

  bitsll_R_1_out1_11 <= if_tmp_0_1_out1_10 sll 1;

  Delay4_P16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_P16_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay4_P16_out1 <= bitsll_R_1_out1_11;
      END IF;
    END IF;
  END PROCESS Delay4_P16_process;


  Delay5_P16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_P16_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay5_P16_out1 <= Delay5_P14_out1;
      END IF;
    END IF;
  END PROCESS Delay5_P16_process;


  R_mant_b_norm_out1_12 <= Delay4_P16_out1 + Delay5_P16_out1;

  Bit_Slice_out1_11 <= R_mant_b_norm_out1_12(25);

  Logical_Operator_out1_12 <=  NOT Bit_Slice_out1_11;

  Bit_Concat_out1_12 <= Delay3_P16_out1 & Logical_Operator_out1_12;

  
  if_tmp_0_1_out1_11 <= R_mant_b_norm_out1_12 WHEN Bit_Slice_out1_11 = '0' ELSE
      Delay4_P16_out1;

  bitsll_R_1_out1_12 <= if_tmp_0_1_out1_11 sll 1;

  R_mant_b_norm_out1_13 <= bitsll_R_1_out1_12 + Delay5_P16_out1;

  Bit_Slice_out1_12 <= R_mant_b_norm_out1_13(25);

  Logical_Operator_out1_13 <=  NOT Bit_Slice_out1_12;

  Bit_Concat_out1_13 <= Bit_Concat_out1_12 & Logical_Operator_out1_13;

  Delay9_P18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_P18_out1 <= to_unsigned(16#0000#, 14);
      ELSIF enb = '1' THEN
        Delay9_P18_out1 <= Bit_Concat_out1_13;
      END IF;
    END IF;
  END PROCESS Delay9_P18_process;


  
  if_tmp_0_1_out1_12 <= R_mant_b_norm_out1_13 WHEN Bit_Slice_out1_12 = '0' ELSE
      bitsll_R_1_out1_12;

  bitsll_R_1_out1_13 <= if_tmp_0_1_out1_12 sll 1;

  Delay10_P18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_P18_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay10_P18_out1 <= bitsll_R_1_out1_13;
      END IF;
    END IF;
  END PROCESS Delay10_P18_process;


  Delay11_P18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_P18_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay11_P18_out1 <= Delay5_P16_out1;
      END IF;
    END IF;
  END PROCESS Delay11_P18_process;


  R_mant_b_norm_out1_14 <= Delay10_P18_out1 + Delay11_P18_out1;

  Bit_Slice_out1_13 <= R_mant_b_norm_out1_14(25);

  Logical_Operator_out1_14 <=  NOT Bit_Slice_out1_13;

  Bit_Concat_out1_14 <= Delay9_P18_out1 & Logical_Operator_out1_14;

  
  if_tmp_0_1_out1_13 <= R_mant_b_norm_out1_14 WHEN Bit_Slice_out1_13 = '0' ELSE
      Delay10_P18_out1;

  bitsll_R_1_out1_14 <= if_tmp_0_1_out1_13 sll 1;

  R_mant_b_norm_out1_15 <= bitsll_R_1_out1_14 + Delay11_P18_out1;

  Bit_Slice_out1_14 <= R_mant_b_norm_out1_15(25);

  Logical_Operator_out1_15 <=  NOT Bit_Slice_out1_14;

  Bit_Concat_out1_15 <= Bit_Concat_out1_14 & Logical_Operator_out1_15;

  Delay_P20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_P20_out1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        Delay_P20_out1 <= Bit_Concat_out1_15;
      END IF;
    END IF;
  END PROCESS Delay_P20_process;


  
  if_tmp_0_1_out1_14 <= R_mant_b_norm_out1_15 WHEN Bit_Slice_out1_14 = '0' ELSE
      bitsll_R_1_out1_14;

  bitsll_R_1_out1_15 <= if_tmp_0_1_out1_14 sll 1;

  Delay1_P20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_P20_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay1_P20_out1 <= bitsll_R_1_out1_15;
      END IF;
    END IF;
  END PROCESS Delay1_P20_process;


  Delay2_P20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_P20_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay2_P20_out1 <= Delay11_P18_out1;
      END IF;
    END IF;
  END PROCESS Delay2_P20_process;


  R_mant_b_norm_out1_16 <= Delay1_P20_out1 + Delay2_P20_out1;

  Bit_Slice_out1_15 <= R_mant_b_norm_out1_16(25);

  Logical_Operator_out1_16 <=  NOT Bit_Slice_out1_15;

  Bit_Concat_out1_16 <= Delay_P20_out1 & Logical_Operator_out1_16;

  
  if_tmp_0_1_out1_15 <= R_mant_b_norm_out1_16 WHEN Bit_Slice_out1_15 = '0' ELSE
      Delay1_P20_out1;

  bitsll_R_1_out1_16 <= if_tmp_0_1_out1_15 sll 1;

  R_mant_b_norm_out1_17 <= bitsll_R_1_out1_16 + Delay2_P20_out1;

  Bit_Slice_out1_16 <= R_mant_b_norm_out1_17(25);

  Logical_Operator_out1_17 <=  NOT Bit_Slice_out1_16;

  Bit_Concat_out1_17 <= Bit_Concat_out1_16 & Logical_Operator_out1_17;

  Delay6_P22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_P22_out1 <= to_unsigned(16#00000#, 18);
      ELSIF enb = '1' THEN
        Delay6_P22_out1 <= Bit_Concat_out1_17;
      END IF;
    END IF;
  END PROCESS Delay6_P22_process;


  
  if_tmp_0_1_out1_16 <= R_mant_b_norm_out1_17 WHEN Bit_Slice_out1_16 = '0' ELSE
      bitsll_R_1_out1_16;

  bitsll_R_1_out1_17 <= if_tmp_0_1_out1_16 sll 1;

  Delay7_P22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_P22_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay7_P22_out1 <= bitsll_R_1_out1_17;
      END IF;
    END IF;
  END PROCESS Delay7_P22_process;


  Delay8_P22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_P22_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay8_P22_out1 <= Delay2_P20_out1;
      END IF;
    END IF;
  END PROCESS Delay8_P22_process;


  R_mant_b_norm_out1_18 <= Delay7_P22_out1 + Delay8_P22_out1;

  Bit_Slice_out1_17 <= R_mant_b_norm_out1_18(25);

  Logical_Operator_out1_18 <=  NOT Bit_Slice_out1_17;

  Bit_Concat_out1_18 <= Delay6_P22_out1 & Logical_Operator_out1_18;

  
  if_tmp_0_1_out1_17 <= R_mant_b_norm_out1_18 WHEN Bit_Slice_out1_17 = '0' ELSE
      Delay7_P22_out1;

  bitsll_R_1_out1_18 <= if_tmp_0_1_out1_17 sll 1;

  R_mant_b_norm_out1_19 <= bitsll_R_1_out1_18 + Delay8_P22_out1;

  Bit_Slice_out1_18 <= R_mant_b_norm_out1_19(25);

  Logical_Operator_out1_19 <=  NOT Bit_Slice_out1_18;

  Bit_Concat_out1_19 <= Bit_Concat_out1_18 & Logical_Operator_out1_19;

  Delay9_P24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_P24_out1 <= to_unsigned(16#00000#, 20);
      ELSIF enb = '1' THEN
        Delay9_P24_out1 <= Bit_Concat_out1_19;
      END IF;
    END IF;
  END PROCESS Delay9_P24_process;


  
  if_tmp_0_1_out1_18 <= R_mant_b_norm_out1_19 WHEN Bit_Slice_out1_18 = '0' ELSE
      bitsll_R_1_out1_18;

  bitsll_R_1_out1_19 <= if_tmp_0_1_out1_18 sll 1;

  Delay10_P24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_P24_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay10_P24_out1 <= bitsll_R_1_out1_19;
      END IF;
    END IF;
  END PROCESS Delay10_P24_process;


  Delay11_P24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_P24_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay11_P24_out1 <= Delay8_P22_out1;
      END IF;
    END IF;
  END PROCESS Delay11_P24_process;


  R_mant_b_norm_out1_20 <= Delay10_P24_out1 + Delay11_P24_out1;

  Bit_Slice_out1_19 <= R_mant_b_norm_out1_20(25);

  Logical_Operator_out1_20 <=  NOT Bit_Slice_out1_19;

  Bit_Concat_out1_20 <= Delay9_P24_out1 & Logical_Operator_out1_20;

  
  if_tmp_0_1_out1_19 <= R_mant_b_norm_out1_20 WHEN Bit_Slice_out1_19 = '0' ELSE
      Delay10_P24_out1;

  bitsll_R_1_out1_20 <= if_tmp_0_1_out1_19 sll 1;

  R_mant_b_norm_out1_21 <= bitsll_R_1_out1_20 + Delay11_P24_out1;

  Bit_Slice_out1_20 <= R_mant_b_norm_out1_21(25);

  Logical_Operator_out1_21 <=  NOT Bit_Slice_out1_20;

  Bit_Concat_out1_21 <= Bit_Concat_out1_20 & Logical_Operator_out1_21;

  Delay3_P26_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_P26_out1 <= to_unsigned(16#000000#, 22);
      ELSIF enb = '1' THEN
        Delay3_P26_out1 <= Bit_Concat_out1_21;
      END IF;
    END IF;
  END PROCESS Delay3_P26_process;


  
  if_tmp_0_1_out1_20 <= R_mant_b_norm_out1_21 WHEN Bit_Slice_out1_20 = '0' ELSE
      bitsll_R_1_out1_20;

  bitsll_R_1_out1_21 <= if_tmp_0_1_out1_20 sll 1;

  Delay4_P26_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_P26_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay4_P26_out1 <= bitsll_R_1_out1_21;
      END IF;
    END IF;
  END PROCESS Delay4_P26_process;


  Delay5_P26_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_P26_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay5_P26_out1 <= Delay11_P24_out1;
      END IF;
    END IF;
  END PROCESS Delay5_P26_process;


  R_mant_b_norm_out1_22 <= Delay4_P26_out1 + Delay5_P26_out1;

  Bit_Slice_out1_21 <= R_mant_b_norm_out1_22(25);

  Logical_Operator_out1_22 <=  NOT Bit_Slice_out1_21;

  Bit_Concat_out1_22 <= Delay3_P26_out1 & Logical_Operator_out1_22;

  
  if_tmp_0_1_out1_21 <= R_mant_b_norm_out1_22 WHEN Bit_Slice_out1_21 = '0' ELSE
      Delay4_P26_out1;

  bitsll_R_1_out1_22 <= if_tmp_0_1_out1_21 sll 1;

  R_mant_b_norm_out1_23 <= bitsll_R_1_out1_22 + Delay5_P26_out1;

  Bit_Slice_out1_22 <= R_mant_b_norm_out1_23(25);

  Logical_Operator_out1_23 <=  NOT Bit_Slice_out1_22;

  Bit_Concat_out1_23 <= Bit_Concat_out1_22 & Logical_Operator_out1_23;

  Delay9_P28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_P28_out1 <= to_unsigned(16#000000#, 24);
      ELSIF enb = '1' THEN
        Delay9_P28_out1 <= Bit_Concat_out1_23;
      END IF;
    END IF;
  END PROCESS Delay9_P28_process;


  
  if_tmp_0_1_out1_22 <= R_mant_b_norm_out1_23 WHEN Bit_Slice_out1_22 = '0' ELSE
      bitsll_R_1_out1_22;

  bitsll_R_1_out1_23 <= if_tmp_0_1_out1_22 sll 1;

  Delay10_P28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_P28_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay10_P28_out1 <= bitsll_R_1_out1_23;
      END IF;
    END IF;
  END PROCESS Delay10_P28_process;


  Delay11_P28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_P28_out1 <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' THEN
        Delay11_P28_out1 <= Delay5_P26_out1;
      END IF;
    END IF;
  END PROCESS Delay11_P28_process;


  R_mant_b_norm_out1_24 <= Delay10_P28_out1 + Delay11_P28_out1;

  Bit_Slice_out1_23 <= R_mant_b_norm_out1_24(25);

  Logical_Operator_out1_24 <=  NOT Bit_Slice_out1_23;

  Bit_Concat_out1_24 <= Delay9_P28_out1 & Logical_Operator_out1_24;

  C_out1_4 <= to_unsigned(16#0000000#, 25);

  
  if_shift_length_1_out1 <= Bit_Concat_out1_24 WHEN shift_length_1_out1_1 = '0' ELSE
      C_out1_4;

  bitsrl_Q_1_out1 <= Bit_Concat_out1_24 srl 1;

  
  if_shift_length_1_out1_1 <= if_shift_length_1_out1 WHEN shift_length_1_out1 = '0' ELSE
      bitsrl_Q_1_out1;

  BitSlice_out1_1 <= if_shift_length_1_out1_1(23 DOWNTO 0);

  Bit_Slice10_out1 <= Delay11_P5_28_out1(4);

  Bit_Slice9_out1 <= Delay11_P5_28_out1(3);

  Bit_Slice7_out1 <= Delay11_P5_28_out1(2);

  Bit_Slice8_out1 <= Delay11_P5_28_out1(1);

  Bit_Slice11_out1 <= Delay11_P5_28_out1(0);

  Bit_Slice_out1_24 <= Bit_Concat_out1_24(2 DOWNTO 0);

  Constant_out1_1 <= '0';

  Bit_Concat_out1_25 <= Bit_Slice_out1_24 & Constant_out1_1;

  Bit_Slice_out1_25 <= Bit_Concat_out1_25(0);

  Bit_Slice1_out1 <= Bit_Concat_out1_25(1);

  Logical_Operator_out1_25 <= Bit_Slice1_out1 OR Bit_Slice_out1_25;

  
  Switch6_out1 <= Bit_Slice_out1_25 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator_out1_25;

  Bit_Slice2_out1 <= Bit_Concat_out1_25(2);

  Logical_Operator1_out1 <= Bit_Slice2_out1 OR Logical_Operator_out1_25;

  Bit_Slice3_out1 <= Bit_Concat_out1_25(3);

  Logical_Operator2_out1 <= Bit_Slice3_out1 OR Logical_Operator1_out1;

  
  Switch7_out1 <= Logical_Operator1_out1 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator2_out1;

  
  Switch3_out1 <= Switch6_out1 WHEN Bit_Slice8_out1 = '0' ELSE
      Switch7_out1;

  Bit_Slice1_out1_1 <= Bit_Concat_out1_24(6 DOWNTO 3);

  Bit_Slice_out1_26 <= Bit_Slice1_out1_1(0);

  Logical_Operator3_out1 <= Bit_Slice_out1_26 OR Logical_Operator2_out1;

  Bit_Slice1_out1_2 <= Bit_Slice1_out1_1(1);

  Logical_Operator_out1_26 <= Bit_Slice1_out1_2 OR Logical_Operator3_out1;

  
  Switch6_out1_1 <= Logical_Operator3_out1 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator_out1_26;

  Bit_Slice2_out1_1 <= Bit_Slice1_out1_1(2);

  Logical_Operator1_out1_1 <= Bit_Slice2_out1_1 OR Logical_Operator_out1_26;

  Bit_Slice3_out1_1 <= Bit_Slice1_out1_1(3);

  Logical_Operator2_out1_1 <= Bit_Slice3_out1_1 OR Logical_Operator1_out1_1;

  
  Switch7_out1_1 <= Logical_Operator1_out1_1 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator2_out1_1;

  
  Switch3_out1_1 <= Switch6_out1_1 WHEN Bit_Slice8_out1 = '0' ELSE
      Switch7_out1_1;

  
  Switch6_out1_2 <= Switch3_out1 WHEN Bit_Slice7_out1 = '0' ELSE
      Switch3_out1_1;

  Bit_Slice2_out1_2 <= Bit_Concat_out1_24(10 DOWNTO 7);

  Bit_Slice_out1_27 <= Bit_Slice2_out1_2(0);

  Logical_Operator3_out1_1 <= Bit_Slice_out1_27 OR Logical_Operator2_out1_1;

  Bit_Slice1_out1_3 <= Bit_Slice2_out1_2(1);

  Logical_Operator_out1_27 <= Bit_Slice1_out1_3 OR Logical_Operator3_out1_1;

  
  Switch6_out1_3 <= Logical_Operator3_out1_1 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator_out1_27;

  Bit_Slice2_out1_3 <= Bit_Slice2_out1_2(2);

  Logical_Operator1_out1_2 <= Bit_Slice2_out1_3 OR Logical_Operator_out1_27;

  Bit_Slice3_out1_2 <= Bit_Slice2_out1_2(3);

  Logical_Operator2_out1_2 <= Bit_Slice3_out1_2 OR Logical_Operator1_out1_2;

  
  Switch7_out1_2 <= Logical_Operator1_out1_2 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator2_out1_2;

  
  Switch3_out1_2 <= Switch6_out1_3 WHEN Bit_Slice8_out1 = '0' ELSE
      Switch7_out1_2;

  Bit_Slice3_out1_3 <= Bit_Concat_out1_24(14 DOWNTO 11);

  Bit_Slice_out1_28 <= Bit_Slice3_out1_3(0);

  Logical_Operator3_out1_2 <= Bit_Slice_out1_28 OR Logical_Operator2_out1_2;

  Bit_Slice1_out1_4 <= Bit_Slice3_out1_3(1);

  Logical_Operator_out1_28 <= Bit_Slice1_out1_4 OR Logical_Operator3_out1_2;

  
  Switch6_out1_4 <= Logical_Operator3_out1_2 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator_out1_28;

  Bit_Slice2_out1_4 <= Bit_Slice3_out1_3(2);

  Logical_Operator1_out1_3 <= Bit_Slice2_out1_4 OR Logical_Operator_out1_28;

  Bit_Slice3_out1_4 <= Bit_Slice3_out1_3(3);

  Logical_Operator2_out1_3 <= Bit_Slice3_out1_4 OR Logical_Operator1_out1_3;

  
  Switch7_out1_3 <= Logical_Operator1_out1_3 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator2_out1_3;

  
  Switch3_out1_3 <= Switch6_out1_4 WHEN Bit_Slice8_out1 = '0' ELSE
      Switch7_out1_3;

  
  Switch7_out1_4 <= Switch3_out1_2 WHEN Bit_Slice7_out1 = '0' ELSE
      Switch3_out1_3;

  
  Switch3_out1_4 <= Switch6_out1_2 WHEN Bit_Slice9_out1 = '0' ELSE
      Switch7_out1_4;

  Bit_Slice4_out1 <= Bit_Concat_out1_24(18 DOWNTO 15);

  Bit_Slice_out1_29 <= Bit_Slice4_out1(0);

  Logical_Operator3_out1_3 <= Bit_Slice_out1_29 OR Logical_Operator2_out1_3;

  Bit_Slice1_out1_5 <= Bit_Slice4_out1(1);

  Logical_Operator_out1_29 <= Bit_Slice1_out1_5 OR Logical_Operator3_out1_3;

  
  Switch6_out1_5 <= Logical_Operator3_out1_3 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator_out1_29;

  Bit_Slice2_out1_5 <= Bit_Slice4_out1(2);

  Logical_Operator1_out1_4 <= Bit_Slice2_out1_5 OR Logical_Operator_out1_29;

  Bit_Slice3_out1_5 <= Bit_Slice4_out1(3);

  Logical_Operator2_out1_4 <= Bit_Slice3_out1_5 OR Logical_Operator1_out1_4;

  
  Switch7_out1_5 <= Logical_Operator1_out1_4 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator2_out1_4;

  
  Switch3_out1_5 <= Switch6_out1_5 WHEN Bit_Slice8_out1 = '0' ELSE
      Switch7_out1_5;

  Bit_Slice5_out1 <= Bit_Concat_out1_24(22 DOWNTO 19);

  Bit_Slice_out1_30 <= Bit_Slice5_out1(0);

  Logical_Operator3_out1_4 <= Bit_Slice_out1_30 OR Logical_Operator2_out1_4;

  Bit_Slice1_out1_6 <= Bit_Slice5_out1(1);

  Logical_Operator_out1_30 <= Bit_Slice1_out1_6 OR Logical_Operator3_out1_4;

  
  Switch6_out1_6 <= Logical_Operator3_out1_4 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator_out1_30;

  Bit_Slice2_out1_6 <= Bit_Slice5_out1(2);

  Logical_Operator1_out1_5 <= Bit_Slice2_out1_6 OR Logical_Operator_out1_30;

  Bit_Slice3_out1_6 <= Bit_Slice5_out1(3);

  Logical_Operator2_out1_5 <= Bit_Slice3_out1_6 OR Logical_Operator1_out1_5;

  
  Switch7_out1_6 <= Logical_Operator1_out1_5 WHEN Bit_Slice11_out1 = '0' ELSE
      Logical_Operator2_out1_5;

  
  Switch3_out1_6 <= Switch6_out1_6 WHEN Bit_Slice8_out1 = '0' ELSE
      Switch7_out1_6;

  
  Switch4_out1 <= Switch3_out1_5 WHEN Bit_Slice7_out1 = '0' ELSE
      Switch3_out1_6;

  Logical_Operator_out1_31 <= Bit_Slice7_out1 OR (Bit_Slice11_out1 OR Bit_Slice8_out1);

  Bit_Slice6_out1 <= Bit_Concat_out1_24(24 DOWNTO 23);

  Bit_Slice_out1_31 <= Bit_Slice6_out1(0);

  Logical_Operator3_out1_5 <= Bit_Slice_out1_31 OR Logical_Operator2_out1_5;

  Bit_Slice1_out1_7 <= Bit_Slice6_out1(1);

  Logical_Operator_out1_32 <= Bit_Slice1_out1_7 OR Logical_Operator3_out1_5;

  
  Switch7_out1_7 <= Logical_Operator3_out1_5 WHEN Logical_Operator_out1_31 = '0' ELSE
      Logical_Operator_out1_32;

  BitSlice_out1_2 <= BitSlice_out1_1(0);

  BitSlice1_out1 <= BitSlice_out1_1(1);

  
  if_tmp_0_1_out1_23 <= R_mant_b_norm_out1_24 WHEN Bit_Slice_out1_23 = '0' ELSE
      Delay10_P28_out1;

  
  R_0_out1 <= '1' WHEN if_tmp_0_1_out1_23 /= to_signed(16#0000000#, 26) ELSE
      '0';

  
  Switch1_out1_1 <= Switch4_out1 WHEN Bit_Slice9_out1 = '0' ELSE
      Switch7_out1_7;

  
  Switch2_out1 <= Switch3_out1_4 WHEN Bit_Slice10_out1 = '0' ELSE
      Switch1_out1_1;

  sticky_bitsll_Q_Q_WordLen_out1 <= R_0_out1 OR Switch2_out1;

  alphabitget_Mant_tmp_2_0_out1 <= BitSlice1_out1 OR sticky_bitsll_Q_Q_WordLen_out1;

  alphabitget_Mant_tmp_1_0_out1 <= BitSlice_out1_2 AND alphabitget_Mant_tmp_2_0_out1;

  alpha0_out1_2 <= '0';

  Bit_Concat_out1_26 <= alpha0_out1_2 & BitSlice_out1_1;

  alpha2_out1 <= to_unsigned(16#0000002#, 25);

  Mant_tmp_2_out1 <= Bit_Concat_out1_26 + alpha2_out1;

  
  if_bitget_Mant_tmp_1_0_out1 <= Bit_Concat_out1_26 WHEN alphabitget_Mant_tmp_1_0_out1 = '0' ELSE
      Mant_tmp_2_out1;

  BitSlice2_out1 <= if_bitget_Mant_tmp_1_0_out1(24);

  DTC2_out1 <= unsigned(s0_out1(7 DOWNTO 0));

  C2_out1_1 <= to_unsigned(16#00#, 8);

  
  s2_out1 <= DTC2_out1 WHEN relop3_out1 = '0' ELSE
      C2_out1_1;

  C4_out1 <= to_unsigned(16#FF#, 8);

  
  s5_out1 <= s2_out1 WHEN relop2_out1 = '0' ELSE
      C4_out1;

  Delay12_P5_28_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay12_P5_28_reg_1 <= (OTHERS => to_unsigned(16#00#, 8));
      ELSIF enb = '1' THEN
        Delay12_P5_28_reg_1(0) <= s5_out1;
        Delay12_P5_28_reg_1(1 TO 11) <= Delay12_P5_28_reg_1(0 TO 10);
      END IF;
    END IF;
  END PROCESS Delay12_P5_28_1_process;

  Delay12_P5_28_out1_1 <= Delay12_P5_28_reg_1(11);

  alpha1_out1_1 <= to_unsigned(16#01#, 8);

  Exp_1_out1 <= Delay12_P5_28_out1_1 + alpha1_out1_1;

  
  if_bitget_Mant_tmp_Mant_tmp_Wor_out1 <= Delay12_P5_28_out1_1 WHEN BitSlice2_out1 = '0' ELSE
      Exp_1_out1;

  C2_out1_2 <= to_unsigned(16#FF#, 8);

  C_out1_5 <= to_unsigned(16#00#, 8);

  
  if_mant_a_0_out1 <= Delay1_P1_out1 WHEN aMantissa_0_out1 = '0' ELSE
      C_out1_5;

  
  if_exp_a_cfType_Exponent_Inf_out1 <= C2_out1_2 WHEN aExponent_cfType_Exponent_I_out1 = '0' ELSE
      if_mant_a_0_out1;

  Delay16_P5_28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay16_P5_28_reg <= (OTHERS => to_unsigned(16#00#, 8));
      ELSIF enb = '1' THEN
        Delay16_P5_28_reg(0) <= if_exp_a_cfType_Exponent_Inf_out1;
        Delay16_P5_28_reg(1 TO 13) <= Delay16_P5_28_reg(0 TO 12);
      END IF;
    END IF;
  END PROCESS Delay16_P5_28_process;

  Delay16_P5_28_out1 <= Delay16_P5_28_reg(13);

  
  if_aExponent_cfType_Exponent_out1 <= if_bitget_Mant_tmp_Mant_tmp_Wor_out1 WHEN Delay12_P5_28_out1 = '0' ELSE
      Delay16_P5_28_out1;

  Constant3_out1 <= to_unsigned(16#00#, 8);

  
  Switch6_out1_7 <= if_aExponent_cfType_Exponent_out1 WHEN Delay1_out1 = '0' ELSE
      Constant3_out1;

  Delay4_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1_1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        Delay4_out1_1 <= Switch6_out1_7;
      END IF;
    END IF;
  END PROCESS Delay4_1_process;


  
  Compare_To_Zero_out1 <= '1' WHEN if_bitget_Mant_tmp_Mant_tmp_Wor_out1 = to_unsigned(16#00#, 8) ELSE
      '0';

  Logical_Operator_out1_33 <= Compare_To_Zero_out1 OR BitSlice2_out1;

  BitSlice3_out1 <= if_bitget_Mant_tmp_1_0_out1(23 DOWNTO 1);

  C_out1_6 <= to_unsigned(16#000000#, 23);

  
  if_bitget_Mant_tmp_Mant_tmp_Wor_1_out1 <= BitSlice3_out1 WHEN Logical_Operator_out1_33 = '0' ELSE
      C_out1_6;

  C3_out1_1 <= to_unsigned(16#000000#, 23);

  
  if_exp_a_cfType_Exponent_Inf_1_out1 <= C3_out1_1 WHEN aExponent_cfType_Exponent_I_out1 = '0' ELSE
      Switch_out1;

  Delay13_P5_28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay13_P5_28_reg <= (OTHERS => to_unsigned(16#000000#, 23));
      ELSIF enb = '1' THEN
        Delay13_P5_28_reg(0) <= if_exp_a_cfType_Exponent_Inf_1_out1;
        Delay13_P5_28_reg(1 TO 13) <= Delay13_P5_28_reg(0 TO 12);
      END IF;
    END IF;
  END PROCESS Delay13_P5_28_process;

  Delay13_P5_28_out1 <= Delay13_P5_28_reg(13);

  
  if_aExponent_cfType_Exponent_1_out1 <= if_bitget_Mant_tmp_Mant_tmp_Wor_1_out1 WHEN Delay12_P5_28_out1 = '0' ELSE
      Delay13_P5_28_out1;

  Constant2_out1 <= to_unsigned(16#000000#, 23);

  
  Switch5_out1 <= if_aExponent_cfType_Exponent_1_out1 WHEN Delay1_out1 = '0' ELSE
      Constant2_out1;

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_out1 <= to_unsigned(16#000000#, 23);
      ELSIF enb = '1' THEN
        Delay5_out1 <= Switch5_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  -- Combine FP sign, exponent, mantissa into 32 bit word
  nfp_out_pack <= Delay3_out1_1 & Delay4_out1_1 & Delay5_out1;

  nfp_out <= std_logic_vector(nfp_out_pack);

END rtl;

