open_system('gaussianFilter');
open_system('gm_gaussianFilter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/gaussianKernel/t5', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/gaussianKernel/t5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/gaussianKernel/t6', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/gaussianKernel/t6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/gaussianKernel/t7', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/gaussianKernel/t7', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/t', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/NeighborhoodCreator_3x3/row1_linebuffer/ram_generic', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/NeighborhoodCreator_3x3/row1_linebuffer/ram_generic', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/BoundaryCheck_3x3/t', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/BoundaryCheck_3x3/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/BoundaryCheck_3x3/t1', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/BoundaryCheck_3x3/t1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/BoundaryCheck_3x3/t2', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/frameBasedGaussianFilter/ImageIn_NeighborhoodCreator/BoundaryCheck_3x3/t2', 1, 1, 'Block not characterized');
