-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj1\hdlsrc\gaussianFilter\gaussianF_ip_src_Input_FIFOs.vhd
-- Created: 2024-06-04 15:10:11
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gaussianF_ip_src_Input_FIFOs
-- Source Path: gaussianFilter/gaussianFilter/Input_FIFOs
-- Hierarchy Level: 1
-- Model version: 8.39
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY gaussianF_ip_src_Input_FIFOs IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enable_in                         :   IN    std_logic;
        imageIn_in                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        imageIn_valid                     :   IN    std_logic;
        enable_out                        :   OUT   std_logic;
        imageIn_out                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        imageIn_ready                     :   OUT   std_logic;
        valid                             :   OUT   std_logic
        );
END gaussianF_ip_src_Input_FIFOs;


ARCHITECTURE rtl OF gaussianF_ip_src_Input_FIFOs IS

  -- Component Declarations
  COMPONENT gaussianF_ip_src_imageIn_FIFO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          imageIn_in                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          valid_in                        :   IN    std_logic;
          should_read                     :   IN    std_logic;
          imageIn_out                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          imageIn_ready                   :   OUT   std_logic;
          imageIn_has_data                :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : gaussianF_ip_src_imageIn_FIFO
    USE ENTITY work.gaussianF_ip_src_imageIn_FIFO(rtl);

  -- Signals
  SIGNAL imageIn_has_data                 : std_logic;
  SIGNAL valid_1                          : std_logic;
  SIGNAL imageIn_out_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_imageIn_FIFO : gaussianF_ip_src_imageIn_FIFO
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              imageIn_in => imageIn_in,  -- uint32
              valid_in => imageIn_valid,
              should_read => valid_1,
              imageIn_out => imageIn_out_tmp,  -- uint32
              imageIn_ready => imageIn_ready,
              imageIn_has_data => imageIn_has_data
              );

  enable_out <= enable_in;

  valid_1 <= enable_in AND imageIn_has_data;

  imageIn_out <= imageIn_out_tmp;

  valid <= valid_1;

END rtl;

