open_system('gm_gaussianFilter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition', 0, 1, 'cp : 8.853 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/uint32Tosingle2/Math Function', 'user1');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/uint32Tosingle2/Math Function', 0, 1, 'cp : 8.853 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/uint32Tosingle2', 'user2');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/uint32Tosingle2', 0, 1, 'cp : 8.853 ns');
