open_system('gaussianFilter');
open_system('gm_gaussianFilter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Divide', 'user1');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Divide', 0, 1, 'Blocks delay absorption: 20 cycles');
hilite_system('gaussianFilter/gaussianFilter/singleToUint32/Divide', 'user1');
annotate_port('gaussianFilter/gaussianFilter/singleToUint32/Divide', 0, 1, 'Blocks delay absorption: 20 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Divide1_recip', 'user1');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Divide1_recip', 0, 1, 'Blocks delay absorption: 33 cycles');
hilite_system('gaussianFilter/gaussianFilter/singleToUint32/Divide1', 'user1');
annotate_port('gaussianFilter/gaussianFilter/singleToUint32/Divide1', 0, 1, 'Blocks delay absorption: 33 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Log', 'user1');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Log', 0, 1, 'Blocks delay absorption: 39 cycles');
hilite_system('gaussianFilter/gaussianFilter/singleToUint32/Log', 'user1');
annotate_port('gaussianFilter/gaussianFilter/singleToUint32/Log', 0, 1, 'Blocks delay absorption: 39 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Math Function1', 'user1');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/singleToUint32/Math Function1', 0, 1, 'Blocks delay absorption: 29 cycles');
hilite_system('gaussianFilter/gaussianFilter/singleToUint32/Math Function1', 'user1');
annotate_port('gaussianFilter/gaussianFilter/singleToUint32/Math Function1', 0, 1, 'Blocks delay absorption: 29 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/uint32Tosingle2/Math Function1', 'user1');
annotate_port('gm_gaussianFilter/gaussianFilter/streaming_matrix_partition/uint32Tosingle2/Math Function1', 0, 1, 'Blocks delay absorption: 12 cycles');
hilite_system('gaussianFilter/gaussianFilter/uint32Tosingle2/Math Function1', 'user1');
annotate_port('gaussianFilter/gaussianFilter/uint32Tosingle2/Math Function1', 0, 1, 'Blocks delay absorption: 12 cycles');
